services:
  test:
    image: youkaichao/pytorch113_cu117_ubuntu2004:openmmlab-ofed
    command: /usr/sbin/sshd -D -e & && sleep infinity
    ports:
      - "3232:22"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '3']
            capabilities: [gpu]